remote_theme: "mmistakes/minimal-mistakes@4.16.3"
minimal_mistakes_skin: "dark"

locale: "en-GB"
title: Stefan Frederik Schouten
repository: "sfschouten/sfschouten.github.io"
analytics:
  provider: "google"
  google:
    tracking_id: UA-22241687-2

author:
  name: "S. F. Schouten"
  bio: "Computer Science student pursuing a career in AI."
  avatar: "/assets/images/profile_pic.jpg"
  location: "Netherlands, Gouda"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:sfschouten@gmail.com
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sfschouten"


paginate: 5
paginate_path: /blog/page:num

plugins:
  - jekyll-include-cache



