markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
minimal_mistakes_skin: "dark"

locale: "en-GB"
title: Stefan Frederik Schouten 
repository: "sfschouten/sfschouten.github.io"
analytics:
  provider: "google"
  google:
    tracking_id: UA-22241687-2

author:
  name: "Stefan F. Schouten"
  bio: "Master's student Artificial Intelligence at the University of Amsterdam."
  avatar: "/assets/images/profile_pic.jpg"
  location: "Netherlands, Gouda"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:sfschouten@gmail.com
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sfschouten"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=Hhxbv4kAAAAJ"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

tag_archive:
  type: liquid
  path: /tags/
category_archive:
  type: liquid
  path: /categories/

paginate: 5
paginate_path: /blog/page:num

plugins:
  - jekyll-include-cache



